#! /bin/bash

name=$1
basename=${name%.*}
ext=${name##*.}
path="/usr/local"


if [ $ext = "py" ]; then
  ex="py"
elif [ $ext = "js" ]; then
  ex="js"
fi

echo 4580 |sudo -S touch $path/bin/$ex/$basename
sudo sh -c "cat $1 > $path/bin/$ex/$basename"
sudo chmod +x $path/bin/$ex/$basename
sudo cp $path/bin/$ex/$basename $path/sbin/$ex/$basename

#$basename
