#! /usr/bin/python3


import os
import sys
import subprocess


os.system(
    f"nautilus /home/surya/temp/mounted_files/{os.path.basename(sys.argv[1])}")
for i in sys.argv[1:]:
    os.system(f"""cp -r {i} {path}""")

path = "/home/surya/temp/mounted_files"
